backend/bookstore/urls.py
from django.urls import path

from backend.bookstore import views as v

app_name = 'bookstore'


urlpatterns = [
    path('', v.BookListView.as_view(), name='book_list'),
    path('<int:pk>/', v.book_detail, name='book_detail'),
    path('create/', v.book_create, name='book_create'),
    path('<int:pk>/update/', v.book_update, name='book_update'),
    path('<int:pk>/delete/', v.book_delete, name='book_delete'),
    path('<int:pk>/like/', v.book_like, name='book_like'),
    path('<int:pk>/unlike/', v.book_unlike, name='book_unlike'),
]

backend/core/urls.py
from django.urls import path

from backend.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

backend/expense/urls.py
from django.urls import path

from backend.expense import views as v

app_name = 'expense'


urlpatterns = [
    path('', v.expense_list, name='expense_list'),
    path('json/', v.expense_json, name='expense_json'),
    path('client/', v.expense_client, name='expense_client'),
    path('create/', v.expense_create, name='expense_create'),
    path('<int:pk>/delete/', v.expense_delete, name='expense_delete'),
    path('expense/paid/', v.expense_paid, name='expense_paid'),
    path('expense/no-paid/', v.expense_no_paid, name='expense_no_paid'),
    path('<int:pk>/', v.expense_detail, name='expense_detail'),
    path('<int:pk>/update/', v.expense_update, name='expense_update'),
]

backend/product/urls.py
from django.urls import path

from backend.product import views as v

app_name = 'product'


urlpatterns = [
    path('', v.product_list, name='product_list'),
    path('category/<int:pk>/create/', v.category_create, name='category_create'),
    path('<int:product_pk>/category/update/', v.category_update, name='category_update'),  # noqa E501
]

backend/state/urls.py
from django.urls import path

from backend.state import views as v

app_name = 'state'


urlpatterns = [
    path('', v.state_list, name='state_list'),
    path('uf/', v.uf_list, name='uf_list'),
    path('result/', v.state_result, name='state_result'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('expense/', include('backend.expense.urls', namespace='expense')),
    path('bookstore/', include('backend.bookstore.urls', namespace='bookstore')),
    path('state/', include('backend.state.urls', namespace='state')),
    path('product/', include('backend.product.urls', namespace='product')),
    path('admin/', admin.site.urls),
]

backend/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

backend/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

backend/core/templates/includes/nav.html
<!-- includes/nav.html -->
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'state:state_list' %}">Estados</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'product:product_list' %}">Produtos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'expense:expense_list' %}">Despesas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'expense:expense_client' %}">Despesas (Client side)</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bookstore:book_list' %}">Livros (Modal)</a>
      </li>
    </ul>
  </div>
</nav>