backend/expense/urls.py
from django.urls import path

from backend.expense import views as v

app_name = 'expense'


urlpatterns = [
    path('', v.expense_list, name='expense_list'),
    path('json/', v.expense_json, name='expense_json'),
    path('client/', v.expense_client, name='expense_client'),
    path('create/', v.expense_create, name='expense_create'),
    path('<int:pk>/delete/', v.expense_delete, name='expense_delete'),
    path('expense/paid/', v.expense_paid, name='expense_paid'),
    path('expense/no-paid/', v.expense_no_paid, name='expense_no_paid'),
    path('<int:pk>/', v.expense_detail, name='expense_detail'),
    path('<int:pk>/update/', v.expense_update, name='expense_update'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('expense/', include('backend.expense.urls', namespace='expense')),
    path('bookstore/', include('backend.bookstore.urls', namespace='bookstore')),
    path('state/', include('backend.state.urls', namespace='state')),
    path('product/', include('backend.product.urls', namespace='product')),
    path('admin/', admin.site.urls),
]

backend/expense/models.py
from django.db import models

from backend.core.models import TimeStampedModel


class Expense(TimeStampedModel):
    description = models.CharField('descrição', max_length=30)
    value = models.DecimalField('valor', max_digits=7, decimal_places=2)
    paid = models.BooleanField('pago', default=False)

    class Meta:
        ordering = ('description',)
        verbose_name = 'despesa'
        verbose_name_plural = 'despesas'

    def __str__(self):
        return self.description

    def to_dict(self):
        return {
            'id': self.id,
            'description': self.description,
            'value': self.value,
            'paid': self.paid,
        }

backend/expense/forms.py
from django import forms

from .models import Expense


class ExpenseForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Expense
        fields = ('description', 'value')
        widgets = {
            'description': forms.TextInput(attrs={'placeholder': 'Descrição', 'autofocus': True}),
            'value': forms.NumberInput(attrs={'placeholder': 'Valor'}),
        }

    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

backend/expense/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from .forms import ExpenseForm
from .models import Expense


def expense_list(request):
    template_name = 'expense/expense_list.html'
    form = ExpenseForm(request.POST or None)

    expenses = Expense.objects.all()

    context = {'object_list': expenses, 'form': form}
    return render(request, template_name, context)


@require_http_methods(['POST'])
def expense_create(request):
    form = ExpenseForm(request.POST or None)

    if form.is_valid():
        expense = form.save()

    context = {'object': expense}
    return render(request, 'expense/hx/expense_hx.html', context)


@require_http_methods(['DELETE'])
def expense_delete(request, pk):
    obj = Expense.objects.get(pk=pk)
    obj.delete()
    return render(request, 'expense/expense_table.html')


@require_http_methods(['POST'])
def expense_paid(request):
    ids = request.POST.getlist('ids')

    # Edita as despesas selecionadas.
    Expense.objects.filter(id__in=ids).update(paid=True)

    # Retorna todas as despesas novamente.
    expenses = Expense.objects.all()

    context = {'object_list': expenses}
    return render(request, 'expense/expense_table.html', context)


@require_http_methods(['POST'])
def expense_no_paid(request):
    ids = request.POST.getlist('ids')

    # Edita as despesas selecionadas.
    Expense.objects.filter(id__in=ids).update(paid=False)

    # Retorna todas as despesas novamente.
    expenses = Expense.objects.all()

    context = {'object_list': expenses}
    return render(request, 'expense/expense_table.html', context)


def expense_detail(request, pk):
    obj = Expense.objects.get(pk=pk)
    form = ExpenseForm(request.POST or None, instance=obj)

    context = {'object': obj, 'form': form}
    return render(request, 'expense/hx/expense_detail_hx.html', context)


def expense_update(request, pk):
    obj = Expense.objects.get(pk=pk)
    form = ExpenseForm(request.POST or None, instance=obj)
    context = {'object': obj}

    if request.method == 'POST':
        if form.is_valid():
            form.save()

    return render(request, 'expense/hx/expense_hx.html', context)


def expense_json(self):
    expenses = Expense.objects.all()
    data = [expense.to_dict() for expense in expenses]
    return JsonResponse({'data': data})


def expense_client(request):
    template_name = 'expense/expense_client.html'
    return render(request, template_name)

backend/expense/templates/expense/expense_client.html
<!-- expense_client.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Lista de Despesas (Client side)</h1>
  <h3>Consumindo API Rest</h3>

  <div hx-ext="client-side-templates">
    <button
      class="btn btn-primary"
      hx-get="{% url 'expense:expense_json' %}"
      hx-swap="innerHTML"
      hx-target="#content"
      mustache-template="foo"
    >
      Clique para carregar os dados
    </button>

    <table class="table">
      <thead>
        <tr>
          <th>Descrição</th>
          <th>Valor</th>
          <th class="text-center">Pago</th>
        </tr>
      </thead>
      <tbody id="content">
      </tbody>
      <template id="foo">
        <!-- Mustache looping -->
        { #data }
        <tr>
          <td>{ description }</td>
          <td>{ value }</td>
          <td class="text-center">
            <!-- Mustache conditional -->
            <!-- http://mustache.github.io/mustache.5.html#Inverted-Sections -->
            { #paid } <i class="fa fa-check-circle ok"></i> { /paid }
            { ^paid } <i class="fa fa-times-circle no"></i> { /paid }
          </td>
        </tr>
        { /data }
      </template>

    </table>
  </div>

{% endblock content %}

{% block js %}
  <script>
    // https://github.com/janl/mustache.js/#custom-delimiters
    Mustache.tags = ['{', '}'];
  </script>
{% endblock js %}

backend/expense/templates/expense/expense_list.html
<!-- expense_list.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Lista de Despesas</h1>
  <div class="row">
    <div class="col">
      <form
        class="form-inline p-3"
        hx-post="{% url 'expense:expense_create' %}"
        hx-target="#expenseTbody"
        hx-indicator=".htmx-indicator"
        hx-swap="afterbegin"
      >
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group p-2">
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
              <small class="text-muted">{{ field.help_text|safe }}</small>
            {% endif %}
          </div>
        {% endfor %}
        <div class="form-group">
          <button
            type="submit"
            class="btn btn-primary ml-2"
          >Adicionar</button>
        </div>
      </form>
    </div>
  </div>

  <div
    class="col"
    hx-include="#checkedExpenses"
    hx-target="#expenseTbody"
  >
    <a
      class="btn btn-outline-success"
      hx-post="{% url 'expense:expense_paid' %}"
    >Pago</a>
    <a
      class="btn btn-outline-danger"
      hx-post="{% url 'expense:expense_no_paid' %}"
    >Não Pago</a>
    <span class="lead"><strong>Bulk update</strong></span>
  </div>

  <div
    id="checkedExpenses"
    class="col pt-2"
  >
    <form>  <!-- Este form é importante pra editar os dados -->
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Descrição</th>
            <th>Valor</th>
            <th class="text-center">Pago</th>
            <th class="text-center">Ações</th>
          </tr>
        </thead>
        <tbody id="expenseTbody">
          {% include "./expense_table.html" %}
        </tbody>
      </table>
    </form>
  </div>

{% endblock content %}

{% block js %}
  <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    });
    htmx.on("htmx:afterSwap", function(evt) {
      if (evt.target.id == 'expenseTbody') {
        document.getElementById('id_description').value = ''
        document.getElementById('id_value').value = ''
      }
    });
  </script>
{% endblock js %}

backend/expense/templates/expense/expense_table.html
<!-- expense_table.html -->
{% for object in object_list %}
  {% include "./hx/expense_hx.html" %}
{% endfor %}